from metadata.ingestion.source.database.customdatabase.metadata import CustomDatabaseSource
from metadata.utils.service_spec.default import DefaultDatabaseSpec

ServiceSpec = DefaultDatabaseSpec(metadata_source_class=CustomDatabaseSource)